# plugin.yml

name: AdvancedMobAI

version: 1.2.1 # 1.2.0 del autor original + port a Paper 26.1.2

main: com.krystalfox.aimobs.AdvancedMobAI

api-version: '26.1'

authors: [Diamondxv0, ll33ee]
description: Mejora la inteligencia artificial de varios mobs hostiles en Minecraft.

commands:
  am:
    description: Gestiona el plugin AdvancedMobAI.
    usage: /<command> reload
    aliases: [advancedmobai]

permissions:
  advancedmobai.reload:
    description: Permite recargar la configuración de AdvancedMobAI.
    default: op